wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697914165.452669
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      3:
      - 23
      4: 3.10.0
      5: 0.15.10
      8:
      - 1
      - 3
      - 5
