wandb_version: 1

loss_function:
  desc: null
  value: focal_dice
batch_size:
  desc: null
  value: 2
backbone:
  desc: null
  value: resnet34
optimizer:
  desc: null
  value: Adam
train_transfer:
  desc: null
  value: imagenet
augmentation:
  desc: null
  value: on_fly
_wandb:
  desc: null
  value:
    python_version: 3.10.0
    cli_version: 0.15.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1697914420.056081
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      3:
      - 7
      - 13
      - 16
      - 23
      - 38
      4: 3.10.0
      5: 0.15.10
      8:
      - 1
      - 3
      - 5
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/mean_iou
      5: 1
      6:
      - 1
    - 1: epoch/weighted_iou
      5: 1
      6:
      - 1
    - 1: epoch/f1
      5: 1
      6:
      - 1
    - 1: epoch/precision
      5: 1
      6:
      - 1
    - 1: epoch/recall
      5: 1
      6:
      - 1
    - 1: epoch/melt_pond_iou
      5: 1
      6:
      - 1
    - 1: epoch/sea_ice_iou
      5: 1
      6:
      - 1
    - 1: epoch/ocean_iou
      5: 1
      6:
      - 1
    - 1: epoch/mean_iou_rounded
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_mean_iou
      5: 1
      6:
      - 1
    - 1: epoch/val_weighted_iou
      5: 1
      6:
      - 1
    - 1: epoch/val_f1
      5: 1
      6:
      - 1
    - 1: epoch/val_precision
      5: 1
      6:
      - 1
    - 1: epoch/val_recall
      5: 1
      6:
      - 1
    - 1: epoch/val_melt_pond_iou
      5: 1
      6:
      - 1
    - 1: epoch/val_sea_ice_iou
      5: 1
      6:
      - 1
    - 1: epoch/val_ocean_iou
      5: 1
      6:
      - 1
    - 1: epoch/val_mean_iou_rounded
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
